// src/server/core/tiles.ts

export interface TileDefinition {
    id: number;
    description: string;
    solid?: boolean;
    pad?: boolean;
    entity?: any;
    known?: boolean;
}

export const TILE_DICTIONARY: Record<number, TileDefinition> = {
    0x00: { id: 0x00, description: "Empty Sky", known: true },
    0x01: { id: 0x01, description: "right side diagonal rock", known: true },
    0x02: { id: 0x02, description: "some rock dent / hole", known: true },
    0x03: { id: 0x03, description: "some rock dent / hole", known: true },
    0x04: { id: 0x04, description: "right side sloped rock", known: true },
    0x05: { id: 0x05, description: "right side sloped rock", known: true },
    0x06: { id: 0x06, description: "right side rock / some rock dent / hole", known: true },
    0x07: { id: 0x07, description: "right side rock / some rock dent / hole", known: true },
    0x08: { id: 0x08, description: "some rock dent / hole", known: true },
    0x09: { id: 0x09, description: "vertical left thin rock start", known: true },
    0x0A: { id: 0x0A, description: "some right side rock", known: true },
    0x0B: { id: 0x0B, description: "diagonal left rock", known: true },
    0x0C: { id: 0x0C, description: "vertical left thin rock with spike", known: true },
    0x0D: { id: 0x0D, description: "some rock", known: true },
    0x0E: { id: 0x0E, description: "rock dent at bottom", known: true },
    0x0F: { id: 0x0F, description: "some rock", known: true },
    0x10: { id: 0x10, description: "horizontal thinner rock transitioning to upper rock / ?? rock", known: true },
    0x11: { id: 0x11, description: "some rock", known: true },
    0x12: { id: 0x12, description: "horizontal rock transitioning to thinner upper rock", known: true },
    0x13: { id: 0x13, description: "rock slope up?", known: true },
    0x14: { id: 0x14, description: "some rock", known: true },
    0x15: { id: 0x15, description: "Base pad", pad: true, known: true },
    0x16: { id: 0x16, description: "full rock", solid: true, known: true },
    0x17: { id: 0x16, description: "some rock", solid: true, known: true },
    0x18: { id: 0x18, description: "vertical left thin rock end", known: true },
    0x19: { id: 0x19, description: "full rock with spike", solid: true, known: true },
    0x1A: { id: 0x1A, description: "right side rock", known: true },
    0x1B: { id: 0x1B, description: "teal brick 2x2", pad: true, known: true },
    0x1C: { id: 0x1C, description: "teal brick", known: true },
    0x1D: { id: 0x1D, description: "teal brick", known: true },
    0x1E: { id: 0x1E, description: "teal brick 2 + bottom left 1", known: true },
    0x1F: { id: 0x1F, description: "teal brick", known: true },
    0x20: { id: 0x20, description: "teal brick left half", known: true },
    0x24: { id: 0x24, description: "teal brick 1 bottom right", known: true },
    0x25: { id: 0x25, description: "some teal brick", known: true },
    0x26: { id: 0x26, description: "some teal brick", known: true },
    0x27: { id: 0x27, description: "some teal brick", known: true },
    0x28: { id: 0x28, description: "Pad Edge Left", pad: true, known: true },
    0x29: { id: 0x29, description: "Landing pad", pad: true, known: true },
    0x2A: { id: 0x2A, description: "Tree", known: true },
    0x2B: { id: 0x2B, description: "Tree", known: true },
    0x2C: { id: 0x2C, description: "Tree", known: true },
    0x2D: { id: 0x2D, description: "Tree", known: true },
    0x2E: { id: 0x2E, description: "Tree", known: true },
    0x31: { id: 0x31, description: "Tree part", known: true },
    0x32: { id: 0x32, description: "Enemy: Tank path (spawn?)", known: true },
    0x33: { id: 0x33, description: "Enemy: Tank path", known: true },
    0x34: { id: 0x34, description: "Tree left bottom", known: true },
    0x35: { id: 0x35, description: "Tree left mid", known: true },
    0x36: { id: 0x36, description: "Tree left top", known: true },
    0x37: { id: 0x37, description: "Tree right mid", known: true },
    0x38: { id: 0x38, description: "Tree right top", known: true },
    0x39: { id: 0x39, description: "Tree related?", known: true },
    0x3A: { id: 0x3A, description: "Tree", known: true },
    0x3B: { id: 0x3B, description: "Race: Blinking checkpoint 1", known: false },
    0x3C: { id: 0x3C, description: "Race: Blinking checkpoint 2", known: false },
    0x3D: { id: 0x3D, description: "Race: Blinking checkpoint 3", known: false },
    0x3E: { id: 0x3E, description: "Race: Blinking checkpoint 4", known: false },
    0x3F: { id: 0x3F, description: "Race: Blinking checkpoint 5", known: false },
    0x40: { id: 0x40, description: "Race: Blinking checkpoint 6", known: false },
    0x41: { id: 0x41, description: "Race: Blinking checkpoint 7", known: false },
    0x42: { id: 0x42, description: "Race: Blinking checkpoint 8", known: false },
    0x43: { id: 0x43, description: "Race: Bottom checkpoint number holder", known: true },
    0x44: { id: 0x44, description: "Race: Bottom checkpoint number holder", known: true },
    0x45: { id: 0x45, description: "Race: Bottom checkpoint number holder", known: true },
    0x46: { id: 0x46, description: "Race: Left-side checkpoint number holder", known: true },
    0x47: { id: 0x47, description: "Race: Left-side checkpoint number holder", known: true },
    0x48: { id: 0x48, description: "Race: Left-side checkpoint number holder", known: true },
    0x49: { id: 0x49, description: "Race: Top checkpoint number holder (3)", known: true },
    0x4A: { id: 0x4A, description: "Race: Top checkpoint number holder (2)", known: true },
    0x4B: { id: 0x4B, description: "Race: Top checkpoint number holder (1)", known: true },
    0x4C: { id: 0x4C, description: "Race: Right-side checkpoint number holder", known: true },
    0x4D: { id: 0x4D, description: "Race: Right-side checkpoint number holder", known: true },
    0x4E: { id: 0x4E, description: "Race: Right-side checkpoint number holder", known: true },

    0x5B: { id: 0x5B, description: "thin standalone rock start", known: true },
    0x5C: { id: 0x5C, description: "thin standalone rock middle", known: true },
    0x5D: { id: 0x5D, description: "thin standalone rock end", known: true },

    0x5E: { id: 0x5E, description: "right side rock", known: true },
    0x5F: { id: 0x5F, description: "right side rock", known: true },
    0x60: { id: 0x60, description: "right side rock", known: true },
    0x61: { id: 0x61, description: "some right side rock", known: true },
    0x62: { id: 0x62, description: "some right side rock", known: true },
    0x63: { id: 0x63, description: "some right side rock", known: true },
    0x64: { id: 0x64, description: "some top-side rock", known: true },
    0x65: { id: 0x65, description: "some top-side rock", known: true },
    0x66: { id: 0x66, description: "some top-side rock", known: true },
    0x67: { id: 0x67, description: "Decorative base", known: true },
    0x68: { id: 0x68, description: "Decorative base", known: true },
    0x69: { id: 0x69, description: "Decorative base", known: true },
    0x6A: { id: 0x6A, description: "Decorative base", known: true },
    0x6B: { id: 0x6B, description: "Decorative base", known: true },
    0x6C: { id: 0x6C, description: "Decorative base", known: true },
    0x6D: { id: 0x6D, description: "Decorative base", known: true },
    0x6E: { id: 0x6E, description: "Decorative base", known: true },
    0x73: { id: 0x73, description: "bottom thin rock?", known: true },
    0x74: { id: 0x74, description: "vertical left thin rock", known: true },
    0x75: { id: 0x75, description: "horizontal thinner upper rock", known: true },
    0x76: { id: 0x76, description: "right side rock", known: true },
    0x77: { id: 0x77, description: "Teal decorative boxes/barrels", known: true },
    0x79: { id: 0x79, description: "Teal decorative boxes/barrels", known: true },
    0x7A: { id: 0x7A, description: "Teal decorative boxes/barrels", known: true },
    0x7B: { id: 0x7B, description: "Teal decorative boxes/barrels", known: true },
    0x7C: { id: 0x7C, description: "Extra base window?", known: true },
    0x7D: { id: 0x7D, description: "Blinking pole", known: true },
    0x7E: { id: 0x7E, description: 'Blinking pole', known: true },
    0x82: { id: 0x82, description: 'blinking pole bottom (smaller than the other?)', known: true },
    0x83: { id: 0x83, description: 'blinking pole top (smaller than the other?)', known: true },
    0x86: { id: 0x86, description: 'Teal decorative boxes/barrels', known: true },
    0x87: { id: 0x87, description: 'Teal decorative boxes/barrels', known: true },
    0x88: { id: 0x88, description: 'Teal decorative boxes/barrels', known: true },
    0x89: { id: 0x89, description: 'Teal decorative boxes/barrels', known: true },
    0x8A: { id: 0x8A, description: 'Teal decorative boxes/barrels', known: true },
    0x8B: { id: 0x8B, description: 'Teal decorative boxes/barrels', known: true },
    0x8F: { id: 0x8F, description: 'Teal decorative boxes/barrels', known: true },

    // 0x00: { id: 0x00, description: '', known: true },
    0xaf: { id: 0xaf, description: 'turret pointing up, shooting three bullets in cone', entity: { type: 'turret', }, known: true },
    0xb0: { id: 0xb0, description: 'turret pointing up, shooting four bullets in cone', entity: { type: 'turret', }, known: true },
    0xb2: { id: 0xb2, description: 'turret pointing up shooting straight up', entity: { type: 'turret', }, known: true },

    // b5 (lvl 49) some turret

    0xb7: { id: 0xb7, description: 'turret pointing east shooting straight east', entity: { type: 'turret', }, known: true },
    0xba: { id: 0xba, description: 'turret pointing up shooting 5 directions (half circle) sideways/upwards (9 or 10 hits needed) -- seen on e.g. lvl 49', entity: { type: 'turret', }, known: true },


    0xBD: { id: 0xBD, description: 'Solid Lethal Walls', solid: true, known: true },

    // 0x00: { id: 0x00, description: '', known: true },
    0xBE: { id: 0xBE, description: 'trigger area for when (af?) turrets start shooting?', known: true },
    0xBF: { id: 0xBF, description: 'trigger area for when (b0?) turrets start shooting?', known: true },
    0xC1: { id: 0xC1, description: 'trigger area for when (b2?) turrets start shooting?', known: true },

    // c4 (lvl49) some turret trigger area

    0xC6: { id: 0xC6, description: 'trigger area for when (b7?) turrets start shooting ... maybe?', known: true },
    0xC9: { id: 0xC9, description: 'trigger area for when (ba?) turrets start shooting ... maybe?', known: true },

    0xCC: { id: 0xCC, description: 'Gravity Well / Trigger', entity: { type: 'trigger', props: { id: 0xCC } }, known: true },
    0xCF: { id: 0xCF, description: 'Gravity Well / Trigger', entity: { type: 'trigger', props: { id: 0xCF } }, known: true },
    // D0 - Pickup package: fuel
    0xD1: { id: 0xD1, description: 'Pickup package / objective', known: true },
    0xD2: { id: 0xD2, description: 'Pickup package / objective', known: true },
    
    0xD6: { id: 0xD6, description: 'Pickup package bonus: double shot; every key press shoots two bullets', known: true },


    0xDA: { id: 0xDA, description: 'Race objective 1 (invisible start line)', known: true },
    0xDB: { id: 0xDB, description: 'Race objective 2 (invisible checkpoint line)', known: true },
    0xDC: { id: 0xDC, description: 'Race objective 3 (invisible checkpoint line)', known: true },
    0xDD: { id: 0xDD, description: 'Race objective 4 (invisible checkpoint line)', known: true },
    0xDE: { id: 0xDE, description: 'Race objective 5 (invisible checkpoint line)', known: true },
    0xDF: { id: 0xDF, description: 'Race objective 6 (invisible checkpoint line)', known: true },
    0xE0: { id: 0xE0, description: 'Race objective 7 (invisible checkpoint line)', known: true },
    0xE1: { id: 0xE1, description: 'Race objective 8 (invisible checkpoint line)', known: true },
    0xE2: { id: 0xE2, description: 'Multi-player P1 race start', entity: { type: 'spawn', props: { player: 1 } }, known: true },
    0xE3: { id: 0xE3, description: 'Multi-player P2 race start', known: true },
    0xE7: { id: 0xE7, description: 'Enemy path', known: true },
    0xEC: { id: 0xEC, description: 'Enemy spawn (e.g. lvl 49)', known: true },
    0xF0: { id: 0xF0, description: 'Enemy path', known: true },
    0xF1: { id: 0xF1, description: 'Enemy path', known: true },
    0xF2: { id: 0xF2, description: 'Enemy path', known: true },
    0xF3: { id: 0xF3, description: 'Enemy path', known: true },
    0xF8: { id: 0xF8, description: 'Enemy path', known: true },
    0xF9: { id: 0xF9, description: 'Enemy path', known: true },
    0xFA: { id: 0xFA, description: 'Enemy path', known: true },
    0xFB: { id: 0xFB, description: 'Enemy path', known: true },
};